Blast4-archive ::= {
  request {
    ident "2.7.1+",
    body queue-search {
      program "blastp",
      service "plain",
      queries bioseq-set {
        seq-set {
          seq {
            id {
              local str "Query_1"
            },
            descr {
              user {
                type str "CFastaReader",
                data {
                  {
                    label str "DefLine",
                    data str ">"
                  }
                }
              }
            },
            inst {
              repr raw,
              mol aa,
              length 9,
              seq-data ncbieaa "MKAISRVLI"
            }
          }
        }
      },
      subject database "mynewdb",
      algorithm-options {
        {
          name "EvalueThreshold",
          value cutoff e-value { 1, 10, 1 }
        },
        {
          name "MaskAtHash",
          value boolean FALSE
        },
        {
          name "SegFiltering",
          value boolean FALSE
        },
        {
          name "WordThreshold",
          value integer 11
        },
        {
          name "WindowSize",
          value integer 40
        },
        {
          name "HitlistSize",
          value integer 500
        },
        {
          name "UngappedMode",
          value boolean FALSE
        },
        {
          name "CompositionBasedStats",
          value integer 2
        },
        {
          name "SmithWatermanMode",
          value boolean FALSE
        },
        {
          name "EffectiveSearchSpace",
          value big-integer 814914
        }
      }
    }
  },
  results {
    alignments {
      {
        type partial,
        dim 2,
        score {
          {
            id str "score",
            value int 42
          },
          {
            id str "blast_score",
            value int 42
          },
          {
            id str "e_value",
            value real { 437301367077272, 10, -16 }
          },
          {
            id str "bit_score",
            value real { 207866144685728, 10, -13 }
          },
          {
            id str "num_ident",
            value int 9
          },
          {
            id str "comp_adjustment_method",
            value int 1
          },
          {
            id str "num_positives",
            value int 9
          },
          {
            id str "hsp_percent_coverage",
            value real { 1, 10, 2 }
          }
        },
        segs denseg {
          dim 2,
          numseg 1,
          ids {
            local str "Query_1",
            swissprot {
              name "MSPA_MYCS2",
              accession "A0QR29",
              release "reviewed"
            }
          },
          starts {
            0,
            0
          },
          lens {
            9
          },
          strands {
            unknown,
            unknown
          }
        }
      }
    },
    masks {
    },
    ka-blocks {
      {
        lambda { 341696339413156, 10, -15 },
        k { 14471814784536, 10, -14 },
        h { 334348319899587, 10, -15 },
        gapped FALSE
      },
      {
        lambda { 267, 10, -3 },
        k { 41, 10, -3 },
        h { 14, 10, -2 },
        gapped TRUE
      }
    },
    search-stats {
      "Effective search space: 814914",
      "Effective search space used: 814914",
      "Length adjustment: 0"
    }
  }
}
